compute-resource:
  refresh: 10
  files:
    protocol: sftp
    location: <hostname of head node>
    path: /home/$CERISE_USERNAME/.cerise

  jobs:
    protocol: ssh
    location: <hostname of head node>
    scheduler: <slurm or torque>
    cwl-runner: $CERISE_API/mdstudio/files/wrap_cwltiny.sh
    queue-name: <or remove to submit to default queue>
    cores-per-node: <number of cores per node>                      # defaults to 32
    slots-per-node: 4                                               # number of MPI ranks per node
    scheduler-options: <e.g. --gres=gpu:1, or remove for none>
